name: Build UI

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/ui/**"
      - "packages/utilities/**"
      - "packages/tailwind-config/**"
      - "packages/typescript-config/**"
      - ".github/workflows/build-ui.yaml"

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    env:
      TURBO_FORCE: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build utilities
        run: yarn build --filter=@repo/utilities

      - name: Type check
        run: yarn check-types

      - name: Lint
        run: yarn lint-ui --filter=@repo/ui

      - name: Build Storybook
        run: yarn build-storybook --filter=@repo/ui
